/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.universidad.juegomd;

/**
 *
 * @author Jorge
 */
public class JuegoMatsDis extends javax.swing.JPanel {

    /**
     * Creates new form Formulario
     */
    public JuegoMatsDis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Pregunta1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pregunta4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Pregunta3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pregunta2 = new javax.swing.JTextArea();
        OpcionA = new javax.swing.JScrollPane();
        Opcion_A = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        OpcionC = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        OpcionD = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        OpcionB = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        Letra1 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        Letra2 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        Letra3 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        Letra4 = new javax.swing.JTextArea();
        BotonRevisar = new javax.swing.JButton();

        Pregunta1.setColumns(20);
        Pregunta1.setRows(5);
        jScrollPane1.setViewportView(Pregunta1);

        Pregunta4.setColumns(20);
        Pregunta4.setRows(5);
        jScrollPane2.setViewportView(Pregunta4);

        Pregunta3.setColumns(20);
        Pregunta3.setRows(5);
        jScrollPane3.setViewportView(Pregunta3);

        Pregunta2.setColumns(20);
        Pregunta2.setRows(5);
        jScrollPane4.setViewportView(Pregunta2);

        Opcion_A.setColumns(20);
        Opcion_A.setRows(5);
        OpcionA.setViewportView(Opcion_A);

        OpcionC.setColumns(20);
        OpcionC.setRows(5);
        jScrollPane6.setViewportView(OpcionC);

        OpcionD.setColumns(20);
        OpcionD.setRows(5);
        jScrollPane7.setViewportView(OpcionD);

        OpcionB.setColumns(20);
        OpcionB.setRows(5);
        jScrollPane8.setViewportView(OpcionB);

        Letra1.setColumns(20);
        Letra1.setRows(5);
        jScrollPane9.setViewportView(Letra1);

        Letra2.setColumns(20);
        Letra2.setRows(5);
        jScrollPane10.setViewportView(Letra2);

        Letra3.setColumns(20);
        Letra3.setRows(5);
        jScrollPane11.setViewportView(Letra3);

        Letra4.setColumns(20);
        Letra4.setRows(5);
        jScrollPane12.setViewportView(Letra4);

        BotonRevisar.setBackground(new java.awt.Color(111, 50, 0));
        BotonRevisar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonRevisar.setForeground(new java.awt.Color(228, 0, 205));
        BotonRevisar.setText("Revisar");
        BotonRevisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRevisarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BotonRevisar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRevisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRevisarMouseClicked
        if(Opcion_A.getText().equals()){
            
        }
        
    }//GEN-LAST:event_BotonRevisarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRevisar;
    private javax.swing.JTextArea Letra1;
    private javax.swing.JTextArea Letra2;
    private javax.swing.JTextArea Letra3;
    private javax.swing.JTextArea Letra4;
    private javax.swing.JScrollPane OpcionA;
    private javax.swing.JTextArea OpcionB;
    private javax.swing.JTextArea OpcionC;
    private javax.swing.JTextArea OpcionD;
    public javax.swing.JTextArea Opcion_A;
    private javax.swing.JTextArea Pregunta1;
    private javax.swing.JTextArea Pregunta2;
    private javax.swing.JTextArea Pregunta3;
    private javax.swing.JTextArea Pregunta4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
